# Generated by Django 4.2 on 2023-09-03 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newcategory',
            name='createdDate',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
