# Generated by Django 4.2 on 2023-09-03 07:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0002_newcategory_createddate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offerReferance', models.CharField(max_length=100)),
                ('offerImage', models.ImageField(blank=True, upload_to='product_image')),
                ('merchant', models.CharField(max_length=100)),
                ('offerType', models.CharField(max_length=100)),
                ('offerSubType', models.CharField(max_length=100)),
                ('voucherCode', models.CharField(max_length=100)),
                ('categoriesCurrent', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('merchantOfferUrl', models.CharField(max_length=100)),
                ('offerClickUrl', models.CharField(max_length=100)),
                ('offerHeadLine', models.CharField(max_length=100)),
                ('offerTitle', models.CharField(max_length=100)),
                ('idealFeedsofferTitle', models.CharField(max_length=100)),
                ('RPofferTitle', models.CharField(max_length=100)),
                ('discountType', models.CharField(max_length=100)),
                ('discountValue', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=300)),
                ('idealfeedsDesc', models.CharField(max_length=300)),
                ('RPDesc', models.CharField(max_length=300)),
                ('termCondition', models.CharField(max_length=300)),
                ('minCartValue', models.CharField(max_length=100)),
                ('BrandRestriction', models.CharField(max_length=100)),
                ('userrestriction', models.CharField(max_length=100)),
                ('startDate', models.DateTimeField()),
                ('endDate', models.DateTimeField()),
                ('displayOrderNo', models.CharField(max_length=100)),
                ('saleEvent', models.CharField(max_length=100)),
                ('blazeText', models.CharField(max_length=100)),
                ('dateCrated', models.DateTimeField(auto_now=True)),
                ('createdBy', models.CharField(max_length=100)),
                ('ownerAgency', models.CharField(max_length=100)),
                ('categoriesAdd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coupon.newcategory')),
            ],
        ),
    ]
