# Generated by Django 4.2 on 2023-09-03 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0003_offer'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewCategoryContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('merchant', models.CharField(max_length=100)),
                ('merchantArticleUrl', models.CharField(max_length=100)),
                ('categoriesCurrent', models.CharField(max_length=100)),
                ('categoriesAdd', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('offerTitle', models.CharField(max_length=100)),
                ('pageMetaDesc', models.CharField(max_length=300)),
                ('content', models.CharField(max_length=300)),
            ],
        ),
    ]
