# Generated by Django 4.2 on 2023-09-06 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0004_newcategorycontent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='categoriesAdd',
            field=models.CharField(max_length=100),
        ),
    ]
