# Generated by Django 4.2 on 2023-09-10 07:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0005_alter_offer_categoriesadd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='categoriesAdd',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coupon.newcategory'),
        ),
    ]
