# Generated by Django 4.2 on 2023-09-11 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0006_alter_offer_categoriesadd'),
    ]

    operations = [
        migrations.AddField(
            model_name='newcategorycontent',
            name='categoryIcon',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
    ]
