# Generated by Django 4.2 on 2023-09-11 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0007_newcategorycontent_categoryicon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newcategorycontent',
            name='categoryIcon',
        ),
    ]
