# Generated by Django 4.2 on 2023-09-14 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0008_remove_newcategorycontent_categoryicon'),
    ]

    operations = [
        migrations.AddField(
            model_name='newcategorycontent',
            name='createdDate',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
